---
title: "Setup"
format: 
  revealjs
---

## Install pyenv (Mac)


- Install [`pyenv`](https://github.com/pyenv/pyenv#installation) using Homebrew
- Setup your [shell environment](https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv): follow the instructions for **your shell**
- Restart your shell

```{.bash}
exec "$SHELL"
```

## Install pyenv (Linux)


- Install [`pyenv`](https://github.com/pyenv/pyenv#automatic-installer) using the automatic installer
- Setup your [shell environment](https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv): follow the instructions for **your shell**
- Restart your shell

```{.bash}
exec "$SHELL"
```

## Install pyenv (Windows)

- **Preferred**: install [`pyenv`](https://github.com/pyenv/pyenv#automatic-installer) in Ubuntu then follow Linux instructions
- Alternatively, install [`pyenv-win`](https://github.com/pyenv-win/pyenv-win):
    - Run Powershell as an administrator
    - Follow [these instructions](https://github.com/pyenv-win/pyenv-win/blob/master/docs/installation.md#powershell)
    - If `pyenv` is not recognized, add these [system settings](https://github.com/pyenv-win/pyenv-win/blob/master/docs/installation.md#add-system-settings) using Powershell
    - Verify the installation by [checking Path and environment variables](https://github.com/pyenv-win/pyenv-win/blob/master/README.md#manually-check-the-settings)

## Install Python 

- Install Python 3.10 using pyenv

```.{bash}
pyenv install 3.10.9
```

- Fork the [`data-structuration-and-transportation`](https://github.com/Tutuchan/data-structuration-and-transportation/fork) repository and clone it

```.{bash}
git clone https://github.com/<your-github-username>/data-structuration-and-transportation.git
```

- Use Python 3.10 for this repository

```.{bash}
pyenv local 3.10.9
```

## Create a virtual environment

```.{bash}
# For Mac / Linux
python -m venv venv # might need to use python3 here
source venv/bin/activate

# For Windows
python -m venv venv # might need to use python3 here
.\venv\Scripts\activate
```